# throw "Have you forgotten to run nixos-anywhere with `--generate-hardware-config nixos-generate-config ./hardware.nix`?"
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake,
  config,
  lib,
  modulesPath,
  ...
}:
let
  me = (import (flake + "/config.nix")).me;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  services.logind = {
    lidSwitchExternalPower = "ignore";
    settings.Login = {
      HandleLidSwitch = "ignore";
      HandleLidSwitchDocked = "ignore";
    };
  };
  systemd.sleep.extraConfig = ''
    AllowSuspend=no
    AllowHibernation=no
    AllowHybridSleep=no
    AllowSuspendThenHibernate=no
  '';

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Mounting external HDD to /mnt/hdd
  fileSystems."/run/media/${me.username}/hdd" = {
    device = "/dev/disk/by-label/HDD";
    fsType = "ext4";
    # `nofail` is imp to prevent boot failure if the drive is not connected.
    options = [
      "defaults"
      "nofail"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
